### ISSUE TITLE
Use a static site generator

### ISSUE THREAD

**Issue by jamesgeorge007** [MadlabsInc/mevn-cli-website#5]
> As per now the website is done in plain html, css and JS. We would like to move it on to a static site generator preferably vuepress

**Comment by jofftiquez** [comment]
What do you think of surge.sh? It's super easy to deploy there.

**Comment by tjeufoolen** [comment]
I like to try this one! :)

**Comment by jamesgeorge007** [comment]
@athyk Go on :+1:

**Comment by tjeufoolen** [comment]
> @athyk Go on 👍

I have created a pull-request for the conversion to Vuepress. 
Let me know if you like it!  😄

**Comment by jamesgeorge007** [comment]
@athyk Kindly have a look at mevn-cli repo
